### ISSUE TITLE
[Translation] Wrong Nature Row/Column Titles

### ISSUE THREAD

**Issue by roytam1** [BernardoGiordano/PKSM#583]
PKSM Version: 5.0.1
PKSM Display Language: JPN

In nature selection screen, instead of showing "-" in first row titles, It shows "Blocked Question Mark".

And also the order of Titles is incorrect, it shows "+/- Atk, Def, Sp.Atk, Sp.Def, Speed" instead of the correct "+/- Atk, Def, Speed, Sp.Atk, Sp.Def"

**Comment by BernardoGiordano** [comment]
Alread fixed in #580

**Comment by roytam1** [comment]
> Alread fixed in #580 

But first issue is not fixed (from the diff shown)
I think using "－" instead of "-" will fix the problem?

**Comment by pass0418** [comment]
https://github.com/BernardoGiordano/PKSM/pull/574/commits/169e76118d232d990269fa3b2f21c2f6ce63f8c9
I already fixed.
Thank you so much!

(Sorry for my bad English!)
